### ISSUE TITLE
Failed to activate the package-developer-toolbar package

### ISSUE THREAD

**Issue by lucasdc6** [idleberg/atom-package-developer-toolbar#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.188.0-d462895
**System**: linux 3.16.0-4-686-pae
**Thrown From**: [package-developer-toolbar](https://github.com/idleberg/atom-package-developer-toolbar) package, v0.3.1
### Stack Trace

Failed to activate the package-developer-toolbar package

```
At /home/lucasdc/.atom/packages/package-developer-toolbar/node_modules/atom-package-deps/lib/index.js:16
      console.error(`[Package-Deps] Unable to get package name for file: ${ fi
                    ^
Unexpected token ILLEGAL

/home/lucasdc/.atom/packages/package-developer-toolbar/node_modules/atom-package-deps/lib/index.js:16
      console.error(`[Package-Deps] Unable to get package name for file: ${ fi
                    ^
SyntaxError: Unexpected token ILLEGAL
  at exports.runInThisContext (vm.js:75:16)
  at Module._compile (module.js:458:25)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.module.exports.activate (/home/lucasdc/.atom/packages/package-developer-toolbar/lib/tool-bar.coffee:5:5)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:240:19)
  at /usr/share/atom/resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:461:21)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -4:09.1 settings-view:open (atom-pane.pane.active)
     -0:44.5 core:paste (atom-text-editor.editor.mini)
     -0:43.0 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
package-developer-toolbar, v0.3.1

# Dev
No dev packages
```

**Comment by idleberg** [comment]
Thanks for reporting the issue.

This package uses `atom-package-deps` to install other Atom packages it depends on. I'm not familiar with the exact requirements of `atom-package-deps`, but leaving that error aside, the toolbar wouldn't work for you since it requests `"atom": ">=1.0.0 <2.0.0"`.

Your version of Atom still uses many API methods that have since been [deprecated](http://blog.atom.io/2015/06/04/deprecated-apis-have-been-removed.html). What's keeping you from upgrading?
